mxid: '@colexdev:matrix.org'
device_id: SWKUCAUUOT
access_token: syt_Y29sZXhkZXY_WHOBPpmANFjnZqahwbzB_1C2wfV
homeserver: https://matrix-client.matrix.org/
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
backspace1_removes_word: true
backspace2_removes_word: false
always_clear_screen: true
data_dir: /home/cole/.local/share/gomuks
cache_dir: /home/cole/.cache/gomuks
history_path: /home/cole/.cache/gomuks/history.db
room_list_path: /home/cole/.cache/gomuks/rooms.gob.gz
media_dir: /home/cole/.cache/gomuks/media
download_dir: /home/cole/Downloads
state_dir: /home/cole/.cache/gomuks/state
