#!/bin/bash

# Function to determine which application to use based on file extension
open_file() {
    file="$1"
    extension="${file##*.}"

    case "$extension" in
        mp4|avi|mkv|webm)
            mpv "$file" ;;
        jpg|jpeg|png|gif|webp)
            nsxiv "$file" ;;
        pdf)
            zathura "$file" ;;
        *)
            echo "Unsupported file format" ;;
    esac
}

# Check if a file is provided as an argument
if [ -z "$1" ]; then
    echo "Usage: open <file>"
    exit 1
fi

# Call the function to open the file
open_file "$1"
