require "cole.options"
require "cole.keymaps"
require "cole.plugins"
require "cole.color"
require "cole.cmp"
require "cole.lsp"
require "cole.plugin_setup"
vim.cmd "let g:vimwiki_list = [{'path': '~/.vimwiki/'}]"
